apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
data:
  default.config: |
    server {
       listen 80;
       location / {
           proxy_pass "http://api-service:4000";
       }
  }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
